language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install flake8
  - python setup.py test
  - python setup.py install
script:
  - flake8 RBFN
  - pytest --cov=RBFN test/test.py  # Run the tests and check for test coverage.
  - python -m RBFN --help  # Check if commandline will be opened.
