language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip3  
install:
  - sudo apt-get update
  - sudo apt-get install lcov
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pip3 install pytest-cov
  - pip3 install flake8
  - python setup.py install
script:
  - flake8
  - pytest --cov=RBFN test/test_travis.py  # Run the tests and check for test coverage with Travis optimized example
  - python -m RBFN --help  # Check if commandline will be opened.
after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --list coverage.info
